name: dolphinsr_dart
description: A spaced-repetition algorithm in dart. Usefull to build a flaschard system in Dart for Flutter or Web.
version: 3.0.0
homepage: https://github.com/JobiJoba/dolphhinsr_dart

environment:
  sdk: '>=2.12.0 <3.0.0'


dependencies:
  equatable: ^2.0.0
  
dev_dependencies:
  test: ^1.16.8
