name: dolphinsr_dart
description: A spaced-repetition algorithm in dart.
version: 1.0.0
author: Johann Baziret
homepage: https://github.com/JobiJoba/dolphhinsr_dart

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  test: ^1.6.0
